[project]
name = "email-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"langchain>=0.2.11",
	"langchain-community>=0.2.7",
	"langchain-ollama>=1.0.0",
]
